### ISSUE TITLE
Need better solution for updating name in response to cell content changes

### ISSUE THREAD

**Issue by mxsdev** [stateful/vscode-runme#566]
In #473, I introduced code that modifies the notebook document on save.

I recently ran into an issue where this makes it impossible to save the document, since the document modification itself makes the document need another save.

I think we need a better solution for updating names based on content changes.

In the short-term, we should probably remove that code, so that people can save their documents properly.

cc @sourishkrout

**Comment by sourishkrout** [comment]
We can probably fix/salvage the implementation using the `onWillSaveTextDocument` event instead. It appears it was introduced for the exact use case where changes need to be handled before saving.

https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L11776-L11796

**Comment by sourishkrout** [comment]
> @sourishkrout
> 
> I tried that, but I was unable to get the unsaved file contents the way you can for a text document. In particular, I couldn't get the associated `NotebookData` with the `NotebookDocument`, which would be necessary for serialization.
> 
> I honestly think the easiest solution is to just re-implement the name generation code from go into javascript - would you be okay with this as a short-term solution?

Let's earmark this to chat about in person this week.

**Comment by sourishkrout** [comment]
@mxsdev this is fixed with the `--index` approach, no?

**Comment by mxsdev** [comment]
@sourishkrout 

It unblocks the issue, but the `--index` approach is still not ideal since the generated command is not very legible or re-usable as the document changes.
